[project]
name = "patient-intake"
version = "0.1.0"
description = "Basic interactive chat interface for AI Patient Intake"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ollama>=0.5.1",
]
